services:
  www:
    build: docker/php
    container_name: cinephoria_php
    ports:
      - 8080:80
    volumes:
      - ./webapp:/var/www/html
      - ./docker/php/vhosts:/etc/apache2/sites-enabled
    networks:
      - cinephoria_net

  mariadb:
    image: mariadb:11.6.2
    container_name: cinephoria_mariadb
    volumes:
      - ./db/mariadb_data:/var/lib/mysql
    environment:
      MARIADB_USER: cinephoria_db_user
      MARIADB_PASSWORD: PW2gV+KmFy5_auMcX
      MARIADB_DATABASE: cinephoria
      MARIADB_ROOT_PASSWORD: n+AzSLV6!Z*2G7ywh~XP
    ports:
      - 33306:3306
    networks:
      - cinephoria_net

  phpmyadmin:
    image: phpmyadmin
    container_name: cinephoria_phpmyadmin
    depends_on:
      - mariadb
    ports:
      - 8780:80
    networks:
      - cinephoria_net
    environment:
      PMA_HOST: mariadb

networks:
  cinephoria_net:
