services:
  www:
    build: docker/php
    container_name: cinephoria_php
    ports:
      - '8080:80'
    user: 1000:1000
    volumes:
      - ./webapp:/var/www/html
      - ./docker/php/vhosts:/etc/apache2/sites-enabled
    networks:
      - cinephoria_net

  mariadb:
    image: mariadb:11.6.2
    container_name: cinephoria_mariadb
    volumes:
      - ./db/mariadb_data:/var/lib/mysql
    environment:
      MARIADB_USER: cinephoria_db_user
      MARIADB_PASSWORD_FILE: /run/secrets/db_password
      MARIADB_DATABASE: cinephoria
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    ports:
      - '33306:3306'
    networks:
      - cinephoria_net
    secrets:
      - db_root_password
      - db_password

  phpmyadmin:
    image: phpmyadmin
    container_name: cinephoria_phpmyadmin
    depends_on:
      - mariadb
    ports:
      - '8780:80'
    networks:
      - cinephoria_net
    environment:
      PMA_HOST: mariadb

networks:
  cinephoria_net:

secrets:
   db_password:
     file: ./secrets/db_password.txt
   db_root_password:
     file: ./secrets/db_root_password.txt
